# markdownlint configuration for nanna-coder
# Compatible with rumdl (Rust markdown linter)
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: true
  tables: false
  headings: true
  strict: false
  stern: false

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - img
    - a
    - kbd
    - sub
    - sup

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  style: fenced

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: ordered

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: true

# MD051/link-fragments - Link fragments should be valid
MD051: true
