---
# yamllint configuration for nanna-coder
# See https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Be flexible with indentation in certain contexts
  indentation:
    spaces: 2
    indent-sequences: consistent

  # Don't require document start markers
  document-start: disable

  # Allow inline mappings for compact YAML
  braces:
    max-spaces-inside: 1

  # Allow truthy values (yes/no, on/off)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Don't enforce quoted strings everywhere
  quoted-strings:
    quote-type: double
    required: only-when-needed

  # Allow comments without space after #
  comments:
    min-spaces-from-content: 1

ignore: |
  .github/
  target/
  result/
