[package]
name = "image-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Container image building utilities for nanna-coder"
repository.workspace = true

[lib]

[dependencies]
thiserror = "1.0"