name: Test Minimal CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test Basic Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run tests
      run: cargo test --workspace --lib